services:
  shairport-sync:
    image: hanfu1997/airplay:latest
    container_name: airplay
    platform: linux/amd64
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./config:/config
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    environment:
      TZ: Asia/Shanghai
    logging:
      options:
        max-size: "200k"
        max-file: "5"

  webui:
    image: hanfu1997/airplay-panel:latest
    container_name: airplay-panel
    platform: linux/amd64
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./config:/config
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Asia/Shanghai
      SHAIRPORT_CONTAINER: airplay
      PANEL_HOST: 0.0.0.0
      PANEL_PORT: "18090"
      # PANEL_USER: admin
      # PANEL_PASSWORD: "www.com123"
    depends_on:
      - shairport-sync
